apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:B01uGQ345qpE8ulzOLPng99XSQBTVzlaf+h75MbI+Nd+9R/30So4vRwipUiYfI8n5Ldvgdp2TorEsyGgLZMNmB/t4+tWMbgxrioT69yHg4QSZd9CRrQZCrHL9/HEZxG+EzegJ1ikGKlmYwQWm+Bug5FM5VTKba5eThMpm5/0twmGlZ3uckvsJNQRqFKI0ZT9RAYnhunu/NfKe9P9avDpLudfg3FnEXZnluxVXPh4z/2WW4zhd8AoZkUVNvFF8fqaj1XY95uPp7blbW2bOy4/jxoRLbTX/RrE9KtdddpmgpiBXgA5fJ3VyPMENNI=,iv:g/d6YHXCzG4E8DQzNUlNwyx2ZgH2GZrVy8vnNRNGPT4=,tag:PgwY5FY1/bjqJ6y8lpa2MA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age15rglv757gd67qtsceu7na09l5y4y2u0phry3ex8n4aj8q8926q3s87vkdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKa1lqSUZIUWRXQjAyTnhQ
            RWFjQ2x2YndrNk9vTjU3STFJQ3hlRXdpYkh3Clppa25jNHZNY3dNNTl6dktHTlJt
            Q296aXVhUGp5S0JPakZZSjlnTS94WTAKLS0tIDBORHFJR2R5RmR1cm93NEc4Nm9w
            UStwR2FvdzVXYnE2VUh4ajdRcTBpdXcKFrbWni96VWH75yI4wrcLwS8LYlMA/4mB
            Hc4iyRZcF/biIIm6ggWJg9ptXcDiy478PrxHkTqC4r1UHUPaK60x4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T15:46:03Z"
    mac: ENC[AES256_GCM,data:gsh0tOUgc0Qh2g8OIe8OmZd/E8DMRnw+R2p9rL7gitfNFuVio3GpsuuclOhMbXCKLwWVBOMemCqqJ7PtfWEOeCpncd4qASfI60qq8u7jUsJOozeooWUZJyHUaqTUUggcX6/CEHNoSZRMXGgV10Ax8raaxbLw9hoMJEUFCjgqJtg=,iv:LUgjhYg1fGqYOJ72gzXLmP0gLTYbbNKJLd7qcE7Aw9A=,tag:5IPahRKgsucYLamq8N2hEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
