apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf 
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: audiobookshelf 
  template:
    metadata:
      labels:
        app: audiobookshelf 
  
    spec:
      initContainers:
        - name: init-storage
          image: ghcr.io/advplyr/audiobookshelf:latest 
          command:
            - sh
            - -c
            - |
              mkdir -p /mnt/audiobooks \
                       /mnt/podcasts \
                       /mnt/config \
                       /mnt/metadata 
          volumeMounts:
            - name: audiobookshelf-data
              mountPath: /mnt
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest 
          volumeMounts:
            - name: audiobookshelf-data
              mountPath: /audiobooks
              subPath: audiobooks
            - name: audiobookshelf-data
              mountPath: /podcasts
              subPath: podcasts
            - name: audiobookshelf-data
              mountPath: /config
              subPath: config
            - name: audiobookshelf-data
              mountPath: /metadata
              subPath: metadta
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          ports:
            - containerPort: 3005 
      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc
