apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:4KqGOF+3g+O/L1WqhoDuGQdv8FEknlujAI5PhzmQmE4F7EVLM5JZQVAKIR47ANBQUMg8BVrX0C/1k62tUnzfEcJjfXFwpTrcsXsVOQIxJ0UhAEqhLmUzRBzu8erpHPpave/t2pRmrcUzGpx3ZjtefcqZfQ7zpUUR5kSaBrkZlys+YsA7gsgTrXi5J/bZ3itMP2Pth5qFrwBe9eajojl+76hqF139cZv0LDxpAQuw/WPaSXcKQLoH2SolngGaryXs/uXwqBkN3vin03OxFUxTa4MHRwieETiicTxvyqOT7tXbe8LV5J7r31VhOyU=,iv:7BnufxmY8NW7IY7vWPrv5F1GBbXRGHkwecIpe83nh34=,tag:Pnpv5tiE2l6lgsKCa25h+Q==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age15rglv757gd67qtsceu7na09l5y4y2u0phry3ex8n4aj8q8926q3s87vkdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbGQ2VzNLN1R0T2Nra211
            Uis5TTkxOTNOUE8reUMzUVo2bEx2aDh3bmlBCnRMNzdaUzhGcnVQUkxINnl6K1Ru
            K2J0cGM3dHpnOEZ1V3VtTjZBODUyZU0KLS0tIHZzMDJYcDM1dzkyTzkwV3g1S2Zw
            elZaNm1qNy93bU5iOUhUMys3N3A2Z1EK1YDVTqKtkbhb5xqWd8syh5snQn3fMx+h
            2BUMT23nihJ+fpK8+5F1KypU4elSiyexW/Na0ZnnsIzaMpRx3g9XKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T10:55:44Z"
    mac: ENC[AES256_GCM,data:Bd+i+Ei8yDfToC5CQKYPuVotnRfcWio08Os05dVM1t+qZiLP17dDXHT6lApiqW8rR6yxaD9g++3F82Zip+9aB5pGgbJ4bXob44hh+2YjqTwSWig08M7Kg3kqLNoLRqOvk9XWK90A85q+r0ciqYUU57+drNQ90ok43QPXubEGjVA=,iv:dmqKL1kQlqnJmN9AFOGOpGrFUVN2ktEF/+q236LIV1c=,tag:ik5Vmsz9Iv5Jmt2aipassQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
