#scratch test-secret used for testing if flux is decrypting secrets correctly
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:8K5ox3xAfMA=,iv:U6JDNutz7963N3i+rgTrf+vsJe6vuZkku6Nugb0h+F0=,tag:p1PmCI5+Nn1HLkGH3GPjVA==,type:str]
    user: ENC[AES256_GCM,data:qQaptQbpUbY=,iv:HcfNb3jM4r1Ko/vLcjBtbzJKaVgbH9NvjtXL6JVWvcY=,tag:BoABoqFu0jQLq/RlHknzVg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age15rglv757gd67qtsceu7na09l5y4y2u0phry3ex8n4aj8q8926q3s87vkdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsV01heDJWTTNvcXdSU0kv
            TzJyNlBSSlFKR0E5cWpzRXVFdTV5bHppRXdBCjhGN083UDFkeUJuMTYrelkyT3Nt
            cG14bW44ZkJqMU9YQUY0UVlaazlmaXcKLS0tIEsrQWhJbklBOGxQUTdKSVphQjEw
            ZERoSzVwYVp2azBHN25rRGhXTHBrUVkKNMSVc7P7v7tgZpytr5DL5W1mrW/vhcto
            Lnjl1BqW+fLYlMuxQhZnulbUjSBUoARGuzCeptitqYcaTmCjxbC4mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:40:59Z"
    mac: ENC[AES256_GCM,data:Erb3MEMOXCWJl1r9p3eM817iZ9VQ3608+gHtZTZVm3ZkdQQeWJJ9HzUL7HMLySsBpTP7PojmDZzapvSve2DAyqK8UYzDGnuWolTfKtzwwZSDF5cO87JK4Jls/g0VeWQZL18Dr15OIcRyCP2cVdkk5tTdQwDPsvIBotWIsjwc5uc=,iv:62lF71+vyFVD9g1NJ+MTzvV+4GSZexPbZEn60s/64ss=,tag:6Q0EaPzmw0ur+d7ohhJaKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
